// Copyright (c) 1992,1997.  Ken Kahn, Animated Programs, All rights reserved
// keep this in synch with sprite.cpp
const short int number_of_sprites = 68;
string sprite_file_names[number_of_sprites] =
	  {"toolboxs",
	   "toolboxa",
		"manwalk",
		"wire",
		"heliofly",
		"frame",
		"heliolnd",
		"mansit",
		"housebt",
		"housebs",
		"doorb",
		"doora",
		"numpad",
		"scale", //"digits",
		"vacuum",
		"expander",
		"copier",
		"tbubble",
		"robot",
		"nest",
		"bird",
		"bomb",
		"notebook",
		"cubby",
		"mouseham",
		"arm",
		"hand",
		"handwand",
		"pumpbtn", //"pictures",
		"hair",
		"hat",
		"vacbtn", // "platform",
		"switch",
		"mansitht",
		"mansithr",
		"houseas",
		"houseat",
		"housecs",
		"housect",
		"doorc",
		"alien",
		"trucki",
		"trucka",
		"trucks",
		"talkbal",
		"wandbtn", //"plate",
		"textpad",
		"notepage",
	"dizzy",
	"dizhair",
	"dizhat",
	"explode",
	"rockdoor",  // "alientlk",
	"hitmiss",
        "ball",
	"paddle",
	"manwalk8",
	"flower",
	"tree",
	"light",
        "synthet", // not a real sprite file
        "user",
        "rocket", // a real one
        "backwall",
        "lftcrnr",
        "rtcrnr",
        "wall",
        "roomdoor"
        };
