// indices for a few special images

#define PERSON_WALKING_EAST1_IMAGE 95
#define PERSON_WALKING_SOUTHEAST8_IMAGE 134
#define PERSON_WALKING_WEST1_IMAGE 210
#define PERSON_WALKING_SOUTHWEST8_IMAGE 233
#define PERSON_WALKING_EAST2_IMAGE 96
#define PERSON_WALKING_EAST3_IMAGE 97
#define PERSON_WALKING_WEST2_IMAGE 211
#define PERSON_WALKING_WEST3_IMAGE 212

#define TOOL_BOX_MORPH16_IMAGE 333

//#define FLOOR_BACKGROUND 1
#define FLOOR1_BACKGROUND 1
#define ROOM_A_BACKGROUND 2
#define ROOM_B_BACKGROUND 3
#define ROOM_C_BACKGROUND 4
#define THOUGHT_BUBBLE_BACKGROUND 5
#define PUZZLE_SINKING_BACKGROUND 1084
#define PUZZLE_CRASH_BACKGROUND 1085
#define PUZZLE_HURT_BACKGROUND 1086
#define PUZZLE_RESCUE_BACKGROUND 1087
#define ROCKET_INSIDES_BACKGROUND 1118
#define OPENING_TITLE_BACKGROUND 1135
#define FLOOR2_BACKGROUND 1136
#define FLOOR3_BACKGROUND 1137
#define PUBLISHER_LOGO_BACKGROUND 1159
#define FLOOR4_BACKGROUND 1171
