// Copyright (c) 1992,1999.  Ken Kahn, Animated Programs, All rights reserved
//#define FIRST_SOUND 1
#define HELICOPTER_SOUND 1
#define BIRD_HATCH_SOUND 2
#define BIRD_FLY_SOUND 3
#define TRUCK_REV_SOUND 4
#define MAGIC_SOUND 5
#define B_WOP_SOUND 6
#define B_YAW_SOUND 7
#define SPIRAL_IN_SOUND 8
#define SPIRAL_OUT_SOUND 9
#define BOOK_DROP_SOUND 10
#define DOOR_CREAK_SOUND 11
#define DUSTBUSTER_SOUND 12
#define EXPLOSION_SOUND 13
#define HAND_PUMP_SOUND 14
#define OUCH_SOUND 15
#define PLOP_SOUND 16
#define POP_SOUND 17
#define WALKING_INSIDE_SOUND 18
#define TYPING_SOUND 19
#define TRAFFIC_SOUND 20
#define PAGE_TURNING_SOUND 21
//#define STEP_SOUND 22
#define NEAT_EFFECT_SOUND 23
#define TRUCK_DRIVE_SOUND 24
#define BIKE_BELL_SOUND 25
#define BOING1_SOUND 26
//#define BOING2_SOUND 27
//#define BOING3_SOUND 28
#define CALCULATING_SOUND 29
#define LOTS_OF_SILLY_SOUNDS 30
#define WHIT_SOUND 31
#define DEFLATING_SOUND 32
#define DOOR_SOUND 33
//#define DOORKNOB_SOUND 34
//#define STEP2_SOUND 35
//#define STEP3_SOUND 36
#define STEP_SOUND 37 // was step4
#define GLASS_HIGH_SOUND 38
#define GLASS_LOW_SOUND 39
//#define COUGH_SOUND 40
//#define SAUCER_LANDING_SOUND 41
//#define ROBOT_SOUND 42
#define SHUTDOWN_SOUND 43
#define SPIT_SOUND 44
#define SWITCH_SOUND 45
#define TELEPORT_SOUND 46
//#define HORSE_TROT_SOUND 47
#define TWING_SOUND 48

#define LAST_SOUND 48



