#define ICON_1	1
#define BITMAP_5	5
#define BITMAP_2	2
#define BITMAP_1	1
#define IDS_INTRO_DEMO	3
#define IDS_EXPLODE_DEMO	4
#define IDS_SWAP_DEMO	5
#define IDS_PONG1_DEMO	6
#define IDS_PONG2_DEMO	7
#define IDS_PONG3_DEMO	8
#define IDS_FIBONACCI_DEMO	9
#define IDS_FACTORIAL_DEMO	10
#define IDS_BANK_DEMO	11
#define IDS_APPEND_DEMO	12
//#define IDS_EXPLODE_INSTRUCTIONS	13
#define IDS_PLAY_PUZZLE_GAME 13
#define IDS_FREE_PLAY	14
#define IDM_SET_OPTIONS 15
#define IDM_HELP 16
#define IDS_LAST_BUTTON IDM_HELP
#define IDS_CONFIRM_PRINT	27
#define IDS_CONFIRM_PRINT2	28
#define IDS_WINDOW_TITLE	29
#define IDS_FORGET_IT	30
#define IDS_EXPLODE_INSTRUCTIONS_FILE1	25
#define IDS_EXPLODE_INSTRUCTIONS_FILE2	26

#define DEMO_ID_OFFSET 50
#define IDS_APPEND_DEMO_FILE IDS_APPEND_DEMO+DEMO_ID_OFFSET
#define IDS_BANK_DEMO_FILE	IDS_BANK_DEMO+DEMO_ID_OFFSET
#define IDS_FACTORIAL_DEMO_FILE	IDS_FACTORIAL_DEMO+DEMO_ID_OFFSET
#define IDS_FIBONACCI_DEMO_FILE	IDS_FIBONACCI_DEMO+DEMO_ID_OFFSET
#define IDS_PONG3_DEMO_FILE	IDS_PONG3_DEMO+DEMO_ID_OFFSET
#define IDS_PONG2_DEMO_FILE	IDS_PONG2_DEMO+DEMO_ID_OFFSET
#define IDS_PONG1_DEMO_FILE	IDS_PONG1_DEMO+DEMO_ID_OFFSET
#define IDS_SWAP_DEMO_FILE	IDS_SWAP_DEMO+DEMO_ID_OFFSET
#define IDS_EXPLODE_DEMO_FILE	IDS_EXPLODE_DEMO+DEMO_ID_OFFSET
#define IDS_INTRO_DEMO_FILE	IDS_INTRO_DEMO+DEMO_ID_OFFSET

#define IDM_NEW            100
#define IDM_OPEN           101
#define IDM_SAVE           102
#define IDM_SAVEAS         103
#define IDM_PRINT          104
#define IDM_PRINTSETUP     105
#define IDM_EXIT           106
#define IDM_SEE_DEMOS	106
#define IDM_RUN_PUZZLES 107
#define IDM_UNDO           200
#define IDM_CUT            201
#define IDM_COPY           202
#define IDM_PASTE          203
#define IDM_LINK           204
#define IDM_LINKS          205
#define IDM_HELPCONTENTS   300
#define IDM_HELPSEARCH     301
#define IDM_HELPHELP       302
#define IDM_ABOUT          303
#define IDM_HELPTOPICS     304
#define IDM_CONTINUE       305

//#define IDC_STATIC -1 // commented out on 281002 since conflicts with MFC

#define DLG_VERFIRST        400
#define IDC_COMPANY			 DLG_VERFIRST
#define IDC_FILEDESC        DLG_VERFIRST+1
#define IDC_PRODVER         DLG_VERFIRST+2
#define IDC_COPYRIGHT       DLG_VERFIRST+3
#define IDC_OSVERSION       DLG_VERFIRST+4
#define IDC_TRADEMARK       DLG_VERFIRST+5
#define DLG_VERLAST         DLG_VERFIRST+5

#define IDC_LABEL           DLG_VERLAST+1

#define ID_COMPANY			1
#define ID_APPNAME			2
#define ID_CMDLINE			        1000
#define IDS_SPEAKERS_ON            1001
#define IDS_NARRATION_FILE_SUFFIX  1002
#define IDS_START_TOONTALK         1003
#define IDS_CDROM_MAY_BE_SLOW      1004
//#define IDS_PUZZLE_SUBDIRECTORY    1004
//#define IDS_NEED_CDROM_TO_CONTINUE 1005
//#define IDS_WARNING_FILE           1006
//#define IDS_COULDNT_OPEN           1007
#define IDS_PLEASE_WAIT 1005


#define IDD_DIALOG4_FIRST 9
#define IDD_OPTIONS_CHANGED 8
#define IDD_DIALOG7	7
#define IDD_DIALOG6	6
#define IDD_DIALOG5	5
#define IDD_DIALOG4	4
#define IDD_DIALOG3	3
#define IDD_DIALOG2	2
#define IDD_DIALOG1	1

#define IDC_OPTION_BACK 500
#define IDC_OPTION_NEXT 501
#define IDC_OPTION_CANCEL 502
#define IDC_OPTION_DONE 503
#define IDC_OPTION_HELP 504
#define IDC_OPTION_QUESTION 505
#define IDC_OPTION_ANSWER1 506
#define IDC_OPTION_ANSWER2 507
#define IDC_OPTION_ANSWER3 508
#define IDC_OPTION_ANSWER4 509
#define IDC_OPTION_ANSWER5 510
#define IDC_OPTION_ANSWER6 511
#define IDC_OPTION_ANSWER7 512
#define IDC_OPTION_EXPLANATION 513

#define IDC_OPTION_ANSWER_TEXT1	552
#define IDC_OPTION_ANSWER_TEXT2	553
#define IDC_OPTION_ANSWER_TEXT3	554
#define IDC_OPTION_ANSWER_TEXT4	555
#define IDC_OPTION_ANSWER_TEXT5	556
#define IDC_OPTION_ANSWER_TEXT6	557
#define IDC_OPTION_ANSWER_TEXT7	558

#define IDC_OPTION_CAPTION 522
#define IDC_OPTION_BACK_TEXT 523
#define IDC_OPTION_NEXT_TEXT 519
#define IDC_OPTION_CANCEL_TEXT 520
#define IDC_OPTION_DONE_TEXT 521

#define IDS_OPTION_NOT_INSTALLED 530
#define IDS_OPTION_AVAILABLE_ONLY_ON_CDROM 531
#define IDS_OPTION_AVAILABLE_ONLY_FOR_32BIT_VERSION 532

#define IDS_OPTIONS_CHANGED_TEXT 533
#define IDS_OPTIONS_CHANGED_TEXT2 534
#define IDS_OPTIONS_RESTORED_TEXT 535
//#define IDC_OPTION_OK_TEXT 535
//#define IDC_OPTION_OK 536

#define IDC_OPTIONS_CHANGED_CAPTION 536

#define IDS_DEMO_FILE_MISSING 537
#define IDS_INSERT_CDROM 538


#define IDS_OPTION1 600
// each option takes ten slots: 0 for question, 1 to 7 for answers, 8 and 9 for explanation
#define IDS_OPTION1_QUESTION IDS_OPTION1
#define IDS_OPTION1_ANSWER1 IDS_OPTION1+1
#define IDS_OPTION1_ANSWER2 IDS_OPTION1+2
#define IDS_OPTION1_ANSWER3 IDS_OPTION1+3
#define IDS_OPTION1_ANSWER4 IDS_OPTION1+4
#define IDS_OPTION1_EXPLANATION IDS_OPTION1+8

#define IDS_OPTION2 610
#define IDS_OPTION2_QUESTION IDS_OPTION2
#define IDS_OPTION2_ANSWER1 IDS_OPTION2+1
#define IDS_OPTION2_ANSWER2 IDS_OPTION2+2
#define IDS_OPTION2_ANSWER3 IDS_OPTION2+3
#define IDS_OPTION2_ANSWER4 IDS_OPTION2+4
#define IDS_OPTION2_ANSWER5 IDS_OPTION2+5
#define IDS_OPTION2_ANSWER6 IDS_OPTION2+6
#define IDS_OPTION2_ANSWER7 IDS_OPTION2+7
#define IDS_OPTION2_EXPLANATION IDS_OPTION2+8

#define IDS_OPTION3 620
#define IDS_OPTION3_QUESTION IDS_OPTION3
#define IDS_OPTION3_ANSWER1 IDS_OPTION3+1
#define IDS_OPTION3_ANSWER2 IDS_OPTION3+2
#define IDS_OPTION3_ANSWER3 IDS_OPTION3+3
#define IDS_OPTION3_ANSWER4 IDS_OPTION3+4
#define IDS_OPTION3_ANSWER5 IDS_OPTION3+5
#define IDS_OPTION3_EXPLANATION IDS_OPTION3+8

#define IDS_OPTION4 630
#define IDS_OPTION4_QUESTION IDS_OPTION4
#define IDS_OPTION4_ANSWER1 IDS_OPTION4+1
#define IDS_OPTION4_ANSWER2 IDS_OPTION4+2
#define IDS_OPTION4_ANSWER3 IDS_OPTION4+3
#define IDS_OPTION4_EXPLANATION IDS_OPTION4+8

#define IDS_OPTION5 640
#define IDS_OPTION5_QUESTION IDS_OPTION5
#define IDS_OPTION5_ANSWER1 IDS_OPTION5+1
#define IDS_OPTION5_ANSWER2 IDS_OPTION5+2
#define IDS_OPTION5_ANSWER3 IDS_OPTION5+3
#define IDS_OPTION5_ANSWER4 IDS_OPTION5+4
#define IDS_OPTION5_ANSWER5 IDS_OPTION5+5
#define IDS_OPTION5_ANSWER6 IDS_OPTION5+6
#define IDS_OPTION5_ANSWER7 IDS_OPTION5+7 // new on 110401
#define IDS_OPTION5_EXPLANATION IDS_OPTION5+8

#define IDS_OPTION6 650
#define IDS_OPTION6_QUESTION IDS_OPTION6
#define IDS_OPTION6_ANSWER1 IDS_OPTION6+1
#define IDS_OPTION6_ANSWER2 IDS_OPTION6+2
#define IDS_OPTION6_EXPLANATION IDS_OPTION6+8

#define IDS_OPTION7 660
#define IDS_OPTION7_QUESTION IDS_OPTION7
#define IDS_OPTION7_ANSWER1 IDS_OPTION7+1
#define IDS_OPTION7_ANSWER2 IDS_OPTION7+2
#define IDS_OPTION7_ANSWER3 IDS_OPTION7+3
#define IDS_OPTION7_EXPLANATION IDS_OPTION7+8

#define IDS_OPTION8 670
#define IDS_OPTION8_QUESTION IDS_OPTION8
#define IDS_OPTION8_ANSWER1 IDS_OPTION8+1
#define IDS_OPTION8_ANSWER2 IDS_OPTION8+2
#define IDS_OPTION8_ANSWER3 IDS_OPTION8+3
#define IDS_OPTION8_ANSWER4 IDS_OPTION8+4
#define IDS_OPTION8_ANSWER5 IDS_OPTION8+5
#define IDS_OPTION8_ANSWER6 IDS_OPTION8+6
#define IDS_OPTION8_ANSWER7 IDS_OPTION8+7
// answers are really generated from list of available languages.
#define IDS_OPTION8_EXPLANATION IDS_OPTION8+8

#define IDS_OPTION9 680
#define IDS_OPTION9_QUESTION IDS_OPTION9
#define IDS_OPTION9_ANSWER1 IDS_OPTION9+1
#define IDS_OPTION9_ANSWER2 IDS_OPTION9+2
#define IDS_OPTION9_ANSWER3 IDS_OPTION9+3
#define IDS_OPTION9_ANSWER4 IDS_OPTION9+4
#define IDS_OPTION9_ANSWER5 IDS_OPTION9+5
#define IDS_OPTION9_ANSWER6 IDS_OPTION9+6
#define IDS_OPTION9_ANSWER7 IDS_OPTION9+7
// answers are really generated from list of available TTS voices
#define IDS_OPTION9_EXPLANATION IDS_OPTION9+8

#define IDS_ENGLISH_CHOICE 2000
#define IDS_SWEDISH_CHOICE 2001

#define IDS_DOC_SUBDIRECTORY_NAME 2100

#define IDD_ABOUT_DIALOG 2200

//#define START_TT_HTML 2500

BOOL InitApplication(HANDLE);
BOOL InitInstance(HANDLE, int);
LRESULT CALLBACK WndProc(HWND, UINT, WPARAM, LPARAM);
//LRESULT CALLBACK About  (HWND, UINT, WPARAM, LPARAM);
typedef char *string;

string copy_string(string source, int length=-1);
string copy_string_without_quotes(string source, int length=-1);
